// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzariaUDS.Infra.Data.Context;

namespace PizzariaUDS.Infra.Data.Migrations
{
    [DbContext(typeof(PizzariaUDSContext))]
    [Migration("20190618014916_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PizzariaUDS.Domain.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PizzariaUDS.Domain.Models.Order", b =>
                {
                    b.OwnsOne("PizzariaUDS.Domain.Models.Pizza", "Pizza", b1 =>
                        {
                            b1.Property<Guid>("Id");

                            b1.Property<int>("EstimatedPreparationTime")
                                .HasColumnName("EstimatedPreparationTime");

                            b1.Property<int>("Flavor")
                                .HasColumnName("Flavor");

                            b1.Property<double>("Price")
                                .HasColumnName("Price");

                            b1.Property<int>("Size")
                                .HasColumnName("Size");

                            b1.HasKey("Id");

                            b1.ToTable("Orders");

                            b1.HasOne("PizzariaUDS.Domain.Models.Order")
                                .WithOne("Pizza")
                                .HasForeignKey("PizzariaUDS.Domain.Models.Pizza", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
